# Generated by Django 5.2.3 on 2025-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
