# Generated by Django 5.2.3 on 2025-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('strs', 'STARTERS'), ('ent', 'Entrees'), ('slds', 'Salads'), ('sps', 'Soups'), ('mscl', 'Miscellaneous'), ('bf', 'Beef'), ('brf', 'Breakfast'), ('dsst', 'Dessert'), ('sf', 'Seafood'), ('sd', 'Side'), ('ch', 'Chicken'), ('prk', 'Pork'), ('ps', 'Past'), ('vgt', 'Vegetarian'), ('lmb', 'Lamb'), ('gt', 'GOAT')], max_length=100),
        ),
    ]
