# Generated by Django 5.2.3 on 2025-07-24 16:40

import recipes.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_added_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[recipes.validations.IsYoutubeLinkValidValidator],
            ),
        ),
    ]
