# Generated by Django 5.2.3 on 2025-07-24 16:44

import recipes.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_youtube_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[recipes.validations.IsYoutubeLinkValidValidator()],
            ),
        ),
    ]
