# Generated by Django 5.2.3 on 2025-07-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_youtube_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["name"]},
        ),
    ]
