# Generated by Django 5.2.3 on 2025-07-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-added_on", "name"]},
        ),
    ]
